### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by romaincaronfr** [Webrom/srv_php_voeux#10]
Ajouter du reporting

Possibilité de voir le taux de charge pour une promo et un module.
Exportation des données

**Comment by AlexisZankowitch** [comment]
![capture du 2015-06-11 17 47 32](https://cloud.githubusercontent.com/assets/12337798/8111407/f5a5170e-1061-11e5-9eef-ada872e6fc2d.png)

TADAAAAAAAAAAAAAAAAAAA

**Comment by AlexisZankowitch** [comment]
ça te plait @Webrom @ColinLeverger ?

**Comment by ColinLeverger** [comment]
l'affichage sur github public des modules sod******\* c'est parfait mon grand ;-) mais sinon ça le fait grave !!
