### ISSUE TITLE
BDD

### ISSUE THREAD

**Issue by romaincaronfr** [Webrom/srv_php_voeux#15]
Utiliser un left join
SELECT FROM CONTENU left join Enseignant on contenu.enseignant=enseignant.login

**Comment by ColinLeverger** [comment]
Whut ?

**Comment by AlexisZankowitch** [comment]
@ColinLeverger C'est pour avoir le nom des enseignants dans la recherche plutot que le login. Le probleme était lorsqu'on voulait récuperer les noms/prenoms des ensignants des contenus avec un join, si le contenu n'avait pas d'enseignant la ligne était ignorée. Si on utilise un left join la ligne sortira meme si enseignant est nul ;)

**Comment by AlexisZankowitch** [comment]
SELECT module,partie,type,hed,nom,prenom from contenu left join enseignant on contenu.enseignant = enseignant.login join module on module.ident=contenu.module;
