### ISSUE TITLE
checkbox export recherche

### ISSUE THREAD

**Issue by AlexisZankowitch** [Webrom/srv_php_voeux#17]
Lorsqu'on fait une recherche sans enseignant la checkbox export devient coché lorsqu'on appuie sur valider, je pense que c'est sans doute un probleme d'ID mais pour te faire chier @ColinLeverger je te créer une issur mouahabhahah
# sucemaqueue

**Comment by ColinLeverger** [comment]
closed (mais l'export se fait tj pas)
