### ISSUE TITLE
Faire une fonction générale pour les vérifs de pourcentages

### ISSUE THREAD

**Issue by ColinLeverger** [Webrom/srv_php_voeux#18]
Y'a 5 fois la même fonction, faut factoriser... je sais pas trop comment, à voir ensemble

**Comment by romaincaronfr** [comment]
Justement, faire une fonction dans le modèle serait le plus logique, genre faire un autre model générale ?

**Comment by AlexisZankowitch** [comment]
je pense pas il faudrait qu'on fasse une classe qui extends ci_controller dans les dossiers systeme de code igniter on balance tout ce dont on a besoin dans son controller et ensuite on ferait hériter nos classes de celle ci
