### ISSUE TITLE
Prompt javascript pour chaque suppression

### ISSUE THREAD

**Issue by ColinLeverger** [Webrom/srv_php_voeux#19]
/\* IF WE HAVE ENOUGHT TIME */ sécuriser chaque action qui supprime de la donnée (pourquoi pas un prompt qui s'affiche quand on clique sur supprimer : êtes vous sûr machin machin

**Comment by romaincaronfr** [comment]
Désolé mais on close ça, pas urgent et comme on considère que nos users ne sont pas bêtes...
