### ISSUE TITLE
Modify Statutaire vérif

### ISSUE THREAD

**Issue by ColinLeverger** [Webrom/srv_php_voeux#20]
a faire après issue 18

**Comment by AlexisZankowitch** [comment]
@ColinLeverger tu peux expliquer un peu cette issue ?

**Comment by ColinLeverger** [comment]
ds profil le mec peut se mettre un statutaire de 920290293029309203 si il veut

**Comment by AlexisZankowitch** [comment]
bah on s'en fiche vu qu'on considere nos utilisateurs intelligent ?

**Comment by romaincaronfr** [comment]
Oui normalement ça on s'en fou, c'est comme il peu se mettre des heures de décharges en négatif...

**Comment by ColinLeverger** [comment]
ça ca a été supprimé c'est plus possible ;)

**Comment by AlexisZankowitch** [comment]
ok donc faut clore l'issue madame @ColinLeverger ;)
