### ISSUE TITLE
Upload image

### ISSUE THREAD

**Issue by romaincaronfr** [Webrom/srv_php_voeux#24]
Si ce n'est pas du jpeg, image uploads et fonctionne. Mais erreur php pour le user.
![capture d ecran 2015-06-10 a 13 50 58](https://cloud.githubusercontent.com/assets/12337595/8081859/b6949100-0f78-11e5-93a1-6245d64ad03b.png)

**Comment by AlexisZankowitch** [comment]
ok on enleve la possibilité du jpeg a voir si ça regle l'issue
