### ISSUE TITLE
Problème css news

### ISSUE THREAD

**Issue by romaincaronfr** [Webrom/srv_php_voeux#25]
![capture d ecran 2015-06-10 a 13 59 50](https://cloud.githubusercontent.com/assets/12337595/8081888/00c14188-0f79-11e5-8699-14522d8f7c42.png)

Ne l'affiche pas de la même façon lorsque c'est une suppression de module.

**Comment by AlexisZankowitch** [comment]
c'est normal, parce que faire une box shadow pour une seule ligne c'est tres moche et en plus la ça fait une differenciation

**Comment by romaincaronfr** [comment]
@TheultimateZank dans ces cas il faudrait envoler l'espace blanc entre le message et date/nom.

**Comment by romaincaronfr** [comment]
*enlever
