### ISSUE TITLE
Design, c'est normal ?

### ISSUE THREAD

**Issue by romaincaronfr** [Webrom/srv_php_voeux#26]
![capture d ecran 2015-06-10 a 22 02 13](https://cloud.githubusercontent.com/assets/12337595/8092755/67d77cb4-0fbc-11e5-958f-961bdb86d547.png)
C'est normal cette bande grise ? Ne manque-t-il pas une image ?

**Comment by AlexisZankowitch** [comment]
c'est en attendant une image de l'enssat
