### ISSUE TITLE
Administration, modification utilisateur

### ISSUE THREAD

**Issue by romaincaronfr** [Webrom/srv_php_voeux#27]
![capture d ecran 2015-06-10 a 22 12 17](https://cloud.githubusercontent.com/assets/12337595/8092933/ccc9306c-0fbd-11e5-9305-04395c711351.png)

Lorsque l'on souhaite modifier un utilisateur et que l'on sélectionne "autre", il n'y a pas de menu qui s'affiche pour écrire un champ personnalisé.

**Comment by ColinLeverger** [comment]
je confirme, ça marche pu, c'est cassé... et puis c'est cassé aussi sur le module d'inscription. je t'issue là dessus, tu sera certainement plusi nspiré que moi, et puis tu sais comment faire ) (du coup : a faire sur le  modification panel admin et panel admistration, merci ma poule) :+1:
