### ISSUE TITLE
Ajout prompt "vous pouvez pas vous inscrire ici" Accueil

### ISSUE THREAD

**Issue by ColinLeverger** [Webrom/srv_php_voeux#30]
pour le moment si tu peux pas t'inscrire à un module dans la page d'accueil ça plante ... todo : rajouter un prompt qui dis : vous n'avez pas assez d'heure ou quoi

**Comment by AlexisZankowitch** [comment]
y a pas de plantage a proprement parler mais pour l'instant il n'y a pas de msg d'erreur qui s'affiche si on peut pas s'inscrire au module
