### ISSUE TITLE
Acceptation utilisateur news

### ISSUE THREAD

**Issue by ColinLeverger** [Webrom/srv_php_voeux#32]
ce n'est pas géré pour le moment ça génère un "vide"

**Comment by AlexisZankowitch** [comment]
c'est moi ça fonctionne, c'est que j'ai sans doute oublié de push ;)
je push et dis moi si y a toujours le bug ou aps

**Comment by AlexisZankowitch** [comment]
![capture du 2015-06-11 17 13 58](https://cloud.githubusercontent.com/assets/12337798/8110572/53db6ddc-105d-11e5-9659-01af48823474.png)
