### ISSUE TITLE
Aide administration

### ISSUE THREAD

**Issue by AlexisZankowitch** [Webrom/srv_php_voeux#4]
Faire une aide pour l'administration : 
lorsque l'on passe la souris (hover) sur le lien d'une box (Contenu, Module, Utilisateurs...) afficher une petite popup expliquant ce qu'on peut faire dans cette partie
utiliser : 
<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="right" title="" data-original-title="Tooltip on right">Right</button>

**Comment by ColinLeverger** [comment]
c'est pas possible :(
